// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tnFpyO7WgxPN1B3VZRUYVgCLUhPjBL0',
    appId: '1:1066867092574:web:248ec53b53f55b39ee98cf',
    messagingSenderId: '1066867092574',
    projectId: 'workout-minds-9687d',
    authDomain: 'workout-minds-9687d.firebaseapp.com',
    storageBucket: 'workout-minds-9687d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbpV57NVbnT64xx9MQyJ2DNVsHO8SYrY',
    appId: '1:1066867092574:android:def814bc025d5efeee98cf',
    messagingSenderId: '1066867092574',
    projectId: 'workout-minds-9687d',
    storageBucket: 'workout-minds-9687d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8tnFpyO7WgxPN1B3VZRUYVgCLUhPjBL0',
    appId: '1:1066867092574:web:e17cac8a57e81756ee98cf',
    messagingSenderId: '1066867092574',
    projectId: 'workout-minds-9687d',
    authDomain: 'workout-minds-9687d.firebaseapp.com',
    storageBucket: 'workout-minds-9687d.firebasestorage.app',
  );
}
